// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    Cli: typeof import('./components/Cli.vue')['default']
    Clock: typeof import('./components/Clock.vue')['default']
    Collection: typeof import('./components/Collection.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    EditorMenu: typeof import('./components/EditorMenu.vue')['default']
    EditorPreview: typeof import('./components/EditorPreview.vue')['default']
    Email: typeof import('./components/Email.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    Fetch: typeof import('./components/Fetch.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    IdeSideBar: typeof import('./components/IdeSideBar.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Music: typeof import('./components/Music.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Product: typeof import('./components/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Shell: typeof import('./components/Shell.vue')['default']
    Text: typeof import('./components/Text.vue')['default']
    Textarea: typeof import('./components/Textarea.vue')['default']
    TextUpload: typeof import('./components/TextUpload.vue')['default']
    ThreeSlider: typeof import('./components/ThreeSlider.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    User: typeof import('./components/User.vue')['default']
    Viper: typeof import('./components/Viper.vue')['default']
    Workspace: typeof import('./components/Workspace.vue')['default']
    Youtube: typeof import('./components/Youtube.vue')['default']
  }
}
